[package]
name = "rust-cef-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
cef = { git = "https://github.com/tauri-apps/cef-rs" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
dirs = "6"
